#!/usr/bin/env bash

# Bind to the external (LAN) IP
BIND="$(getent hosts $HOSTNAME | awk '{print $1}')"

if [ -z "$MASTER" ]
then
	next="-bootstrap"
else
	next="-join=$MASTER"
fi

echo "USE IP $BIND"
exec consul agent -config-dir /etc/consul.d/bootstrap $next -dc $DATACENTER;